- name: enable COPR atom repo
  become: yes
  shell: dnf copr enable helber/atom -y

- name: install atom
  become: yes
  dnf: name=atom state=latest

- name: ensure that the .atom directory exists
  file: path="/home/{{ user }}/.atom/packages" state=directory
