- name: check whether docker exists
  shell: command -v docker >/dev/null 2>&1
  ignore_errors: yes
  register: result

- name: copy Docker repo file
  become: yes
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo
  when: result|failed

- name: install docker
  become: yes
  dnf: name=docker state=present
  when: result|failed

- name: add docker group
  become: yes
  group: name=docker state=present

- name: ensure that user is in the 'docker' group
  become: yes
  user: name="{{ user }}" group=docker append=yes

- name: start the docker service (but do not enable is at boot)
  become: yes
  service:
    name: docker
    state: started
    enabled: "{{ docker_boot_start }}"
