- name: install TLP packages
  become: yes
  dnf: name="{{ item }}" state=present
  with_items:
    - tlp
    - tlp-rdw

- name: start TLP
  become: yes
  service:
    name: tlp
    state: started
    enables: yes
